#################################################################################       
# Build a dataframe from scratch for the yearly site covariates by plugging in 
#    data extracted from GIS layers or generated by hand for years.
#################################################################################

### YEARS ###
#
# the colext pdf has years as characters, so I guess that's what I'll do too
     years_vec <- as.character(2013:2018)
     years_m <- matrix(years_vec, nrow = 60, ncol = 6, 
                    byrow = T)
          # years_vec is the data to put in the matrix 
          # nrow is the number of rows the matrix will have, I set it equal to 
          #    the number of rows in the survey variables dataframe incase I 
          #    add another site or something and the number of sites changes.
          # ncol is the number of columns the matrix will have.
          # byrow=T means the data will be repeated each row from the one above
          #    it instead of repeating the same value in a row across all columns
     colnames(years_m) <- paste0("Year_",2013:2018)
     
### PRECIPITATION ###

# read in data
precip <- read.csv("prep_data/Precip_WY.csv")

# keep only the entries that I need for AC, CH, EP, LT & the precip values
precip_sub <- precip[1:60,5:10]

# names the rows to keep track of them
rownames(precip_sub) <- precip$Site[1:60]

# scale the values, so they have mean 0 and SD of 1 because that data is 
#    continuous
precip_scaled <- scale(precip_sub)

# that's the final matrix too because it was pre-formatted mostly 
precip_m <- precip_scaled

# clean up
rm(precip, precip_sub, precip_scaled)
     
### MERGE ### - DON'T NEED TO MERGE

#yearly_covar <- as.data.frame(cbind(years_m,precip_m))
     
# clean up
#rm(years_vec,years,yearly)
